### ISSUE TITLE
Support for autoscaling/v2beta2

### ISSUE THREAD

**Issue by KieranP** [stefanprodan/istio-hpa#4]
Changed HPA metric format from:

```yaml
metrics:
  - type: Object
    object:
      metricName: istio-requests-total
      target:
        apiVersion: v1
        kind: Pod
        name: podinfo
      targetValue: 10
```

to:

```yaml
metrics:
- type: Object
  object:
    metric:
      name: istio-requests-total
    describedObject:
      apiVersion: v1
      kind: Pod
      name: podinfo
    target:
      type: Value
      value: 10
```
